AllCops:
  Include:
    - 'attributes/*.rb'
    - 'recipes/*.rb'
    - 'providers/*.rb'
    - 'resources/*.rb'
    - 'test/**/*.rb'
    - 'spec/**/*.rb'
Documentation:
  Enabled: false
AlignParameters:
  Enabled: false
CyclomaticComplexity:
  Max: 10
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 40
Style/MethodName:
  Enabled: false
Style/FileName:
  Enabled: false
# otherwise knife-cookbook-doc style complains
Style/LeadingCommentSpace:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Next:
  Enabled: false
